sonar.organization=arboleda5252
sonar.projectKey=Arboleda5252_drinkware2
sonar.projectName=drinkware2

# Ruta al código fuente (normalmente la raíz '.' o 'src')
sonar.sources=src

sonar.exclusions=**/.next/**,**/node_modules/**,**/out/**,**/public/**,**/*.config.js,**/*.config.ts

# Configuración específica para TypeScript
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
