sonar.organization=arboleda5252
sonar.projectKey=Arboleda5252_drinkware2
sonar.projectName=drinkware2

# Ruta al código fuente (normalmente la raíz '.' o 'src')
sonar.sources=.

# Opcional: Excluir archivos como pruebas o dependencias
# sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts
